### ISSUE TITLE
Code Copy and Code Block Enhancer plugin incompatibility

### ISSUE THREAD

**Issue by NomarCub** [nothingislost/obsidian-codemirror-options#5]
The syntax highlighting fix is unfortunately incompatible with the [Code Block Enhancer](https://github.com/nyable/obsidian-code-block-enhancer) and [Code Copy](https://github.com/superDuperCyberTechno/obsidian-code-copy) plugin.

I've opened an issue in [all](https://github.com/superDuperCyberTechno/obsidian-code-copy/issues/8) [respective](https://github.com/nyable/obsidian-code-block-enhancer/issues/8) [repos](https://github.com/nothingislost/obsidian-codemirror-options/issues/5), hopefully you three can find a solution to this.

**Comment by nothingislost** [comment]
I've looked into this and our plugins just aren't compatible. CodeMirror rewrites the entire contents of the pre/code block with its own syntax highlighting. This rewrite is destroying the buttons and line numbers that those other plugins are creating.

I'll add line numbers and a copy button to this plugin to address the gaps.

**Comment by nothingislost** [comment]
Check out https://github.com/nothingislost/obsidian-codemirror-options/releases/tag/0.1.0 and see if that fills the gap

**Comment by nothingislost** [comment]
Anything else you're missing from those other plugins or are we good to close this?

**Comment by NomarCub** [comment]
Thanks for the fix!
The copying always has a newline at the end.
The button is more convenient in the top right for longer code blocks.
Should I open separate issues for these?

Interestingly, the Code Copy plugin seems to function mostly now.
Also some blocks with no language are left without copy buttons from either plugin, that would have a button from Code Copy.

**Comment by nothingislost** [comment]
Yeah, the code copy plugin shows up now because I'm more closely mimicking the DOM structure used by the default prism.js plugin. That plugin definitely breaks when enabling line numbers though due to how I added them into the code blocks. My copy logic has to remove the line numbers explicitly before adding the text to the clipboard.

Lets create separate issues for these specific issues and close this one. Shouldn't be too difficult to address those.
